docs: Update information on extending Superset assets
openedx/openedx-aspects pull request #226
Opened 2024-06-21 20:08 UTC by bmtcril

Adding information to update how do do this, including the new (currently unreleased)  updates that should go out in 1.0.3: https://github.com/openedx/tutor-contrib-aspects/pull/881

2024-06-21 20:16 UTC, Ian2012 commented on docs/how-tos/superset_extra_assets.rst
> +tempates directory, when ``tutor config save is run``. For example
```suggestion
tempates directory, when ``tutor config save`` is run. For example 
```

2024-06-21 20:17 UTC, Ian2012 commented on docs/how-tos/superset_extra_assets.rst
> +Now you can export your Superset dashboard, which it will download to your local computer
```suggestion
Now you can export your Superset dashboard, which will download to your local computer
```

2024-06-24 14:37 UTC, saraburns1 requested changes

2024-06-24 14:37 UTC, saraburns1 commented on docs/how-tos/superset_extra_assets.rst
> +Developers user the `superset-extra-assets` patch to add extra assets to Superset and those
```suggestion
Developers can use the `superset-extra-assets` patch to add extra assets to Superset and those
```

2024-06-24 15:25 UTC, saraburns1 approved these changes

2024-06-24 16:40 UTC, merged